# Dependencies
markdown: kramdown
highlighter:      rouge

# Permalinks
#permalink:        /:categories/:title
permalink:  none

collections:
  projects:
    output: true       
    permalink: /projects/:path



# Setup
title:            Omkar Masurkar
tagline:          ''
description:      'Hello World!'
url:              https://omkarm.github.io/
baseurl:          /
author:
  name:           'Omkar Masurkar'
  url:            

# paginate:         5

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/sravps7/omalphastreak/omkar/
